#端口号
server:
  port: 80

#JDBC
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.81.254/unforum?useSSL=false&serverTimezone=GMT&characterEncoding=utf8
    username: unpassant
    password: 1940097836
    type: com.alibaba.druid.pool.DruidDataSource

#accessToken数据
github:
  client:
    id: 73f8ee46b1910380454e
    secret: 0a99eb611354abac7d43c90af75e74b681a9d8aa
    Redirect_uri: http://43.139.81.254/callback

#数据库驼峰转换
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

#日志
logging:
  file:
    name: logs/unforum.log
  level:
    root: info
    life:
      unpassant:
        unforum:
          mapper: debug
  logback:
    rollingpolicy:
      max-history: 10
      max-file-size: 30MB

